import type { ToolMeta } from "@/lib/types";

export const TOOLS: ToolMeta[] = [
  {
    slug: "shot-quality",
    name: "Shot Quality Predictor",
    short: "Shot Quality",
    tagline: "Grade any shot's expected value from location, defender distance, clock, and context.",
    category: "Prediction",
    accent: "ember",
    icon: "Crosshair",
    keywords: ["shot", "quality", "qSQ", "expected points", "defender", "shot clock"],
  },
  {
    slug: "player-similarity",
    name: "Player Similarity Engine",
    short: "Similarity",
    tagline: "HoopRadar finds statistical twins by playstyle, usage, shooting, and defense.",
    category: "Player Analysis",
    accent: "cyan",
    icon: "GitCompareArrows",
    keywords: ["similar", "comp", "comparison", "like", "twin", "hoopradar"],
  },
  {
    slug: "fantasy-draft",
    name: "Fantasy Draft Assistant",
    short: "Fantasy Draft",
    tagline: "Rank picks by projected value, category scarcity, team needs, and punt fits.",
    category: "Prediction",
    accent: "gold",
    icon: "Trophy",
    keywords: ["fantasy", "draft", "punt", "category", "scarcity", "pick"],
  },
  {
    slug: "trade-machine",
    name: "Trade Machine",
    short: "Trade Machine",
    tagline: "Build cap-legal multi-team trades and grade the roster impact for everyone.",
    category: "Team & Strategy",
    accent: "ember",
    icon: "ArrowLeftRight",
    keywords: ["trade", "salary", "cap", "apron", "deal", "multi-team"],
  },
  {
    slug: "clutch",
    name: "Clutch Dashboard",
    short: "ClutchGene",
    tagline: "Who actually delivers in the final five — efficiency, poise, and shot difficulty.",
    category: "Player Analysis",
    accent: "rose",
    icon: "Timer",
    keywords: ["clutch", "late game", "fourth quarter", "closer", "clutchgene"],
  },
  {
    slug: "march-madness",
    name: "March Madness Predictor",
    short: "March Madness",
    tagline: "Simulate the bracket with efficiency, seeding, SOS, form, and upset odds.",
    category: "Prediction",
    accent: "gold",
    icon: "Brackets",
    keywords: ["march madness", "ncaa", "bracket", "tournament", "upset", "seed"],
  },
  {
    slug: "ref-bias",
    name: "RefBias Analyzer",
    short: "RefBias",
    tagline: "Surface foul-call patterns by team, venue, drives, and star-whistle effect.",
    category: "Player Tools",
    accent: "cyan",
    icon: "Scale",
    keywords: ["ref", "foul", "bias", "whistle", "free throw", "officiating"],
  },
  {
    slug: "lineup-optimizer",
    name: "Lineup Optimizer",
    short: "Lineup Optimizer",
    tagline: "Find the best 5-man unit by spacing, defense, scoring, playmaking, and balance.",
    category: "Team & Strategy",
    accent: "mint",
    icon: "Users",
    keywords: ["lineup", "five", "rotation", "spacing", "fit", "unit"],
  },
  {
    slug: "injury-risk",
    name: "Injury Risk Predictor",
    short: "Injury Risk",
    tagline: "Model breakdown risk from workload, age, minutes, rest, and missed games.",
    category: "Prediction",
    accent: "rose",
    icon: "HeartPulse",
    keywords: ["injury", "risk", "workload", "load management", "rest", "health"],
  },
  {
    slug: "win-probability",
    name: "Win Probability Tracker",
    short: "Win Probability",
    tagline: "Live win odds from margin, time, possession, home court, and team strength.",
    category: "Prediction",
    accent: "cyan",
    icon: "Activity",
    keywords: ["win probability", "live", "odds", "margin", "comeback", "wp"],
  },
  {
    slug: "highlight-clipper",
    name: "Highlight Auto-Clipper",
    short: "Auto-Clipper",
    tagline: "Detect highlight moments from motion, crowd-audio spikes, and event cues.",
    category: "Content & Media",
    accent: "ember",
    icon: "Scissors",
    keywords: ["highlight", "clip", "video", "auto", "reel", "moments"],
  },
  {
    slug: "recruit-rank",
    name: "RecruitRank",
    short: "RecruitRank",
    tagline: "Turn prep stats and film into a recruiting-grade profile and scouting report.",
    category: "Player Tools",
    accent: "gold",
    icon: "GraduationCap",
    keywords: ["recruit", "high school", "prospect", "stars", "rating", "college"],
  },
  {
    slug: "contract-value",
    name: "Contract Value Analyzer",
    short: "Contract Value",
    tagline: "Spot overpaid and underpaid players: salary vs production, age, and availability.",
    category: "Player Analysis",
    accent: "mint",
    icon: "DollarSign",
    keywords: ["contract", "value", "overpaid", "underpaid", "salary", "surplus"],
  },
  {
    slug: "playtype",
    name: "PlayType Classifier",
    short: "PlayType",
    tagline: "Classify possessions: pick-and-roll, iso, transition, post-up, spot-up, and cuts.",
    category: "Team & Strategy",
    accent: "cyan",
    icon: "Shapes",
    keywords: ["playtype", "pick and roll", "iso", "transition", "post up", "possession"],
  },
  {
    slug: "team-chemistry",
    name: "Team Chemistry Simulator",
    short: "Chemistry",
    tagline: "Predict fit from usage overlap, spacing, defense, passing, and positional need.",
    category: "Team & Strategy",
    accent: "mint",
    icon: "Atom",
    keywords: ["chemistry", "fit", "usage overlap", "pairing", "roster fit"],
  },
  {
    slug: "momentum",
    name: "Momentum Tracker",
    short: "Momentum",
    tagline: "Detect runs, timeout swings, substitution effects, and quarter-by-quarter shifts.",
    category: "Team & Strategy",
    accent: "ember",
    icon: "TrendingUp",
    keywords: ["momentum", "run", "swing", "timeout", "comeback"],
  },
  {
    slug: "development-curve",
    name: "Development Curve Predictor",
    short: "Dev Curve",
    tagline: "Project a young player's growth with age curves, comps, and historical patterns.",
    category: "Prediction",
    accent: "cyan",
    icon: "LineChart",
    keywords: ["development", "growth", "young", "projection", "age curve", "ceiling"],
  },
  {
    slug: "shot-chart",
    name: "Shot Chart Generator",
    short: "Shot Chart",
    tagline: "Interactive court map of makes, misses, hot zones, frequency, and expected points.",
    category: "Content & Media",
    accent: "ember",
    icon: "Target",
    keywords: ["shot chart", "hot zone", "court", "heatmap", "zones"],
  },
  {
    slug: "debate",
    name: "Debate Evidence Finder",
    short: "Debate",
    tagline: "Pose any hoops debate and get evidence-backed cases for both sides.",
    category: "Content & Media",
    accent: "gold",
    icon: "MessagesSquare",
    keywords: ["debate", "argue", "vs", "better", "evidence", "goat"],
  },
  {
    slug: "role-classifier",
    name: "Role Classifier",
    short: "Role Classifier",
    tagline: "Cluster players into archetypes: 3&D, rim protector, creator, stretch big, slasher.",
    category: "Player Analysis",
    accent: "cyan",
    icon: "Boxes",
    keywords: ["role", "archetype", "cluster", "3 and d", "type"],
  },
  {
    slug: "training-tracker",
    name: "Training Tracker",
    short: "Training",
    tagline: "Log workouts, shooting reps, conditioning, streaks, goals, and progress charts.",
    category: "Player Tools",
    accent: "mint",
    icon: "Dumbbell",
    keywords: ["training", "workout", "reps", "streak", "habit", "log"],
  },
  {
    slug: "scouting-report",
    name: "AI Scouting Report",
    short: "Scouting",
    tagline: "Auto-generate strengths, weaknesses, role, comp, and development priorities.",
    category: "Player Analysis",
    accent: "gold",
    icon: "ClipboardList",
    keywords: ["scouting", "report", "strengths", "weaknesses", "profile"],
  },
  {
    slug: "game-recap",
    name: "Game Recap Auto-Writer",
    short: "Game Recap",
    tagline: "Convert a box score into an ESPN-style recap with top performers and turning points.",
    category: "Content & Media",
    accent: "ember",
    icon: "Newspaper",
    keywords: ["recap", "box score", "story", "writeup", "summary"],
  },
  {
    slug: "pick-and-roll",
    name: "Pick-and-Roll Analyzer",
    short: "Pick & Roll",
    tagline: "Grade handler / roll-man duos by points per possession, turnovers, and shot quality.",
    category: "Team & Strategy",
    accent: "ember",
    icon: "Workflow",
    keywords: ["pick and roll", "pnr", "handler", "roll man", "ppp", "two man"],
  },
  {
    slug: "news-sentiment",
    name: "News Sentiment Tracker",
    short: "Sentiment",
    tagline: "Track how media sentiment around a player or team trends over time.",
    category: "Content & Media",
    accent: "cyan",
    icon: "Rss",
    keywords: ["news", "sentiment", "media", "headlines", "narrative"],
  },
  {
    slug: "award-predictor",
    name: "Award Predictor",
    short: "Awards",
    tagline: "Forecast MVP, DPOY, ROTY, and 6MOY from stats, record, seeding, and voting trends.",
    category: "Prediction",
    accent: "gold",
    icon: "Award",
    keywords: ["award", "mvp", "dpoy", "roty", "6moy", "voting"],
  },
  {
    slug: "roster-builder",
    name: "Roster Builder Game",
    short: "Roster Builder",
    tagline: "Draft a team under the cap and score offense, defense, chemistry, and balance.",
    category: "Team & Strategy",
    accent: "mint",
    icon: "LayoutGrid",
    keywords: ["roster", "build", "salary cap", "game", "gm"],
  },
  {
    slug: "defensive-impact",
    name: "Defensive Impact Dashboard",
    short: "Defense",
    tagline: "Rank defenders with rim protection, steals, matchup load, and on/off context.",
    category: "Player Analysis",
    accent: "cyan",
    icon: "Shield",
    keywords: ["defense", "defensive", "stopper", "rim protect", "dpoy"],
  },
  {
    slug: "iq-quiz",
    name: "Basketball IQ Quiz",
    short: "IQ Quiz",
    tagline: "Test your read of spacing, defense, and decisions through live scenarios.",
    category: "Player Tools",
    accent: "rose",
    icon: "Brain",
    keywords: ["quiz", "iq", "scenario", "strategy", "test", "learn"],
  },
  {
    slug: "underrated",
    name: "Underrated Player Finder",
    short: "Underrated",
    tagline: "Surface overlooked players: high efficiency, strong plus-minus, low pay and noise.",
    category: "Player Analysis",
    accent: "mint",
    icon: "Gem",
    keywords: ["underrated", "overlooked", "hidden", "value", "sleeper"],
  },
];

export const TOOL_MAP: Record<string, ToolMeta> = Object.fromEntries(
  TOOLS.map((t) => [t.slug, t]),
);

export const CATEGORIES = [
  "Prediction",
  "Player Analysis",
  "Team & Strategy",
  "Content & Media",
  "Player Tools",
] as const;

// Volt Court per-category accents — saturated but soft on the cool dark field.
export const CATEGORY_COLOR: Record<string, string> = {
  Prediction: "#C8F23F", // volt
  "Player Analysis": "#5ED4F0", // ice cyan
  "Team & Strategy": "#5FD49A", // mint
  "Content & Media": "#E8C463", // warm gold
  "Player Tools": "#F07AA8", // signal pink
};

export function categoryColor(category: string): string {
  return CATEGORY_COLOR[category] ?? "#C8F23F";
}

export function getTool(slug: string): ToolMeta | undefined {
  return TOOL_MAP[slug];
}
