/**
 * CourtCommand seed script.
 *
 * Emits the in-memory mock dataset (src/lib/data) as SQL INSERTs and a JSON
 * snapshot so it can populate the Postgres/Supabase schema in db/schema.sql.
 *
 *   npx tsx scripts/seed.ts          # writes db/seed.sql and db/seed.json
 *
 * When you wire a live NBA feed, replace this generator's source with your
 * provider's API and keep the same table shape — the app keeps working.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { PLAYERS, TEAMS, SALARY_CAP, LUXURY_TAX, FIRST_APRON, SECOND_APRON } from "../src/lib/data";

const esc = (v: string) => v.replace(/'/g, "''");

function teamsSql(): string {
  return TEAMS.map(
    (t) =>
      `insert into teams (abbr,name,city,conference,division,color,color2,wins,losses,ortg,drtg,pace,payroll) values ('${t.abbr}','${esc(t.name)}','${esc(t.city)}','${t.conf}','${t.div}','${t.color}','${t.color2}',${t.wins},${t.losses},${t.ortg},${t.drtg},${t.pace},${t.payroll});`,
  ).join("\n");
}

function playersSql(): string {
  return PLAYERS.map(
    (p) =>
      `insert into players (id,name,team,pos,age,height_in,weight_lb,experience,salary,gp,mpg,ppg,rpg,apg,spg,bpg,topg,fg_pct,tp_pct,ft_pct,tpa,usage,ts_pct,per,bpm,net_rtg) values ('${p.id}','${esc(p.name)}','${p.team}','${p.pos}',${p.age},${p.htIn},${p.wtLb},${p.exp},${p.salary},${p.gp},${p.mpg},${p.ppg},${p.rpg},${p.apg},${p.spg},${p.bpg},${p.topg},${p.fgp},${p.tpp},${p.ftp},${p.tpa},${p.usg},${p.tsp},${p.per},${p.bpm},${p.netRtg});`,
  ).join("\n");
}

function capSql(): string {
  return `insert into cap_rules (season,salary_cap,luxury_tax,first_apron,second_apron) values ('2024-25',${SALARY_CAP},${LUXURY_TAX},${FIRST_APRON},${SECOND_APRON});`;
}

mkdirSync("db", { recursive: true });
const sql = [
  "-- Generated by scripts/seed.ts — do not edit by hand.",
  "begin;",
  teamsSql(),
  playersSql(),
  capSql(),
  "commit;",
].join("\n\n");

writeFileSync("db/seed.sql", sql + "\n");
writeFileSync("db/seed.json", JSON.stringify({ teams: TEAMS, players: PLAYERS }, null, 2));

console.log(`Seeded ${TEAMS.length} teams and ${PLAYERS.length} players → db/seed.sql, db/seed.json`);
